---

- name: "Ensure user {{ user_name }} exists"
  user:
    name: "{{ user_name }}"
    append: yes
    groups: wheel
    state: present

- name: Ensure {{ user_name }} ssh key exists in authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '{{ repository_root_dir }}/administration/users/{{ user_name}}.pub') }}"
    exclusive: yes
    state: present
  vars:
    repository_root_dir: "{{ lookup('env', 'PWD') }}"

