- name: Configure maven-slave AMI
  hosts: all 
  become: true
  become_user: root
  vars_files: ./vars/main.yml
  tasks:
    - name: Install Java
      yum:
        name: "java-{{ java_version }}"
        state: latest
    
    - name: Create directory maven
      file:
        path: /opt/maven
        state: directory

    - name: Unarchive downloaded Maven
      unarchive:
        src: "http://www-eu.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: /opt/maven
        remote_src: yes
        extra_opts: --strip-components=1

    - name: Setup Environment Variable
      shell: |
        cat <<EOF | sudo tee /etc/profile.d/maven.sh
        export MAVEN_HOME=/opt/maven
        export PATH=\$PATH:\$MAVEN_HOME/bin
        EOF

    - name: Source the file maven.sh
      shell: source /etc/profile.d/maven.sh
